# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout changes
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        cache: pip
        python-version: '3.11'

    - name: Setup requirements
      run: pip install -e .[dev]
      if: steps.cache-env.outputs.cache-hit != 'true'

    - name: Test with pytest
      run: pytest tests.py
